services:
  - type: web
    name: voxa
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
